

export const soundfile=[
    'Kelly’s eye',
    'Kaala dhan',
    'Cup of tea',
    'Hum doh, humare doh',
    'Punjab mail',
    'Half a dozen',
    'Lucky',
    'Garden gate',
    'Brighton line',
    'Boris’s den.',
   'Legs eleven',
    'One dozen',
   'Unlucky for some',
   'Valentine’s Day',
    'Young and keen',
    'Sweet 16 and never been kissed',
    'Dancing queen',
    'Coming of age',
    'Goodbye teens',
  'One score',
    'Key of the door',
    ' Two little ducks',
   ' Thee and me',
    ' Two dozen',
    ' Duck and dive',
    'Pick and mix',
 'Gateway to heaven',
    'In a state, Over weight',
    'Rise and shine',
   'Dirty Gertie',
  ' Get up and run',
   'Buckle my shoe',
   'Dirty knee',
  ' Ask for more',
  ' Jump and jive',
   'Three dozen',
   'More than eleven',
   'Christmas cake',
   '39 steps',
   'Life begins',
   'Time for fun',
   'Winnie the Pooh',
   'Down on your knees',
   'Chor & chor, All the fours',
   'Halfway there',
   'Up to tricks',
   'Four and seven',
   'Four dozen',
   'PC',
   'Half a century',
   'Tweak of the thumb',
   ' Danny La Rue',
   'Here comes Herbie',
   'Clean the floor',
   'Snakes alive',
   'Shotts Bus',
   'Heinz varieties',
   'Make them wait',
   ' Brighton Line',
   'Five dozen',
   'Baker’s bun',
   'Turn the screw',
   'Tickle me ',
   'Red raw',
   'Old age pension',
   'Clickety click',
   'Stairway to heaven',
   'Saving Grace',
   'Favourite of mine',
   'Three score and ten',
   ' Bang on the drum',
   'Six dozen',
   'Queen bee',
   'Hit the floor',
   'Strive and strive',
   'Trombones',
   'Sunset strip',
   '39 more steps',
   'One more time',
   'Eight and blank',
   'Stop and run',
   'Straight on through',
   ' Time for tea',
   'Seven dozen',
   'Staying alive',
   'Between the sticks',
   'Torquay in Devon',
   'Two fat ladies',
   ' Nearly there',
   'Top of the shop'

]